version: "3.9"

services:
  api:
    build: ./
    command: ./wait-for-postgres.sh db ./api
    container_name: api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=1234

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5436:5432